---
mqti:
  workers: 4

mqtt:
  host: "mosquitto"
  port: "1883"
  client_id: "mqti"

influxdb:
  host: "influxdb"
  port: "8086"

mappings:
  - mqtt:
      topic: "temperature"
    influxdb:
      database: "iot"
      measurement: "temperature"

  - mqtt:
      topic: "owntracks"
    influxdb:
      database: "owntracks"
      measurement: "location"
      mungers:
        tags:
          from:
          - tid: "device_id"
        geohash:
          lat_field: "lat"
          lng_field: "lon"
          result_field: "geohash"
